# Kubernetes Job template for GCP validator testing
#
# This template embeds the validate.sh script directly in the job spec, avoiding the need
# to build and push a container image for development. Uses a standard Alpine image.
#
# Prerequisites:
#   Apply RBAC resources: kubectl apply -f rbac.yaml
#
# Placeholders to replace before applying:
# - <scenario>: The test scenario (e.g., success, failure, hang, crash, invalid-json, missing-status)
# - <namespace>: The Kubernetes namespace
# - <status-reporter-image>: The status-reporter container image
#   Example: quay.io/rh-ee-dawang/status-reporter:dev-04e8d0a
#
# Usage:
#   sed -e 's|<scenario>|success|g' \
#       -e 's|<namespace>|default|g' \
#       -e 's|<status-reporter-image>|quay.io/rh-ee-dawang/status-reporter:dev-04e8d0a|g' \
#       job-template.yaml | kubectl apply -f -
#
apiVersion: batch/v1
kind: Job
metadata:
  name: fake-validator-<scenario>
  namespace: <namespace>
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 310  # 300 + 10 second buffer
  template:
    metadata:
      labels:
        app: gcp-validator
        job-name: fake-validator-<scenario>
    spec:
      serviceAccountName: gcp-validator
      restartPolicy: Never

      # Volumes
      volumes:
      - name: results
        emptyDir: {}

      containers:
      # Adapter container (fake-validator)
      - name: fake-validator
        image: alpine:3.19
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e

            # Default configuration
            RESULTS_PATH="${RESULTS_PATH:-/results/adapter-result.json}"
            SIMULATE_RESULT="${SIMULATE_RESULT:-success}"

            echo "Fake GCP Validator starting..."
            echo "Simulating result: ${SIMULATE_RESULT}"
            echo "Results path: ${RESULTS_PATH}"

            # Ensure results directory exists
            RESULTS_DIR=$(dirname "${RESULTS_PATH}")
            mkdir -p "${RESULTS_DIR}"

            case "${SIMULATE_RESULT}" in
              success)
                echo "Writing success result..."
                cat > "${RESULTS_PATH}" <<EOF
            {
              "status": "success",
              "reason": "ValidationPassed",
              "message": "GCP environment validated successfully (simulated)",
              "details": {
                "simulation": true,
                "checks_run": 5,
                "checks_passed": 5,
                "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              }
            }
            EOF
                echo "Success result written to ${RESULTS_PATH}"
                exit 0
                ;;

              failure)
                echo "Writing failure result..."
                cat > "${RESULTS_PATH}" <<EOF
            {
              "status": "failure",
              "reason": "MissingPermissions",
              "message": "Service account lacks required IAM permissions (simulated)",
              "details": {
                "simulation": true,
                "missing_permissions": [
                  "compute.instances.list",
                  "iam.serviceAccounts.get"
                ],
                "service_account": "fake-sa@project.iam.gserviceaccount.com",
                "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              }
            }
            EOF
                echo "Failure result written to ${RESULTS_PATH}"
                exit 1
                ;;

              hang)
                echo "Simulating hang (sleeping indefinitely)..."
                sleep 9999999
                ;;

              crash)
                echo "Simulating crash (exiting without writing results)..."
                exit 1
                ;;

              invalid-json)
                echo "Writing invalid JSON result..."
                echo "{ this is not valid json }" > "${RESULTS_PATH}"
                exit 0
                ;;

              missing-status)
                echo "Writing result with missing status field..."
                cat > "${RESULTS_PATH}" <<EOF
            {
              "reason": "TestReason",
              "message": "This result is missing the status field"
            }
            EOF
                exit 0
                ;;

              *)
                echo "Unknown SIMULATE_RESULT value: ${SIMULATE_RESULT}"
                echo "Valid values: success, failure, hang, crash, invalid-json, missing-status"
                echo "Defaulting to success..."
                cat > "${RESULTS_PATH}" <<EOF
            {
              "status": "success",
              "reason": "ValidationPassed",
              "message": "GCP environment validated successfully (default simulation)",
              "details": {
                "simulation": true,
                "note": "Unknown SIMULATE_RESULT value, defaulted to success"
              }
            }
            EOF
                exit 0
                ;;
            esac
        env:
        # Configure simulation scenario
        # Valid values: success, failure, hang, crash, invalid-json, missing-status
        - name: SIMULATE_RESULT
          value: "<scenario>"
        - name: RESULTS_PATH
          value: "/results/adapter-result.json"
        volumeMounts:
        - name: results
          mountPath: /results
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

      # Status reporter sidecar
      - name: status-reporter
        image: <status-reporter-image>
        imagePullPolicy: Always
        env:
        # Required environment variables
        - name: JOB_NAME
          value: "fake-validator-<scenario>"
        - name: JOB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        # Optional configuration
        - name: RESULTS_PATH
          value: "/results/adapter-result.json"
        - name: POLL_INTERVAL_SECONDS
          value: "2"
        - name: MAX_WAIT_TIME_SECONDS
          value: "300"
        - name: CONDITION_TYPE
          value: "Available"
        - name: LOG_LEVEL
          value: "info"
        - name: ADAPTER_CONTAINER_NAME
          value: "fake-validator"

        volumeMounts:
        - name: results
          mountPath: /results
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
